#!/bin/sh
########################################################################
# corecount - Prints the number of CPU cores found on this system
#
# Copyright © 2017-2018 by Warren Young
# 
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS LISTED ABOVE BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
# THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# 
# Except as contained in this notice, the names of the authors above shall
# not be used in advertising or otherwise to promote the sale, use or
# other dealings in this Software without prior written authorization from
# those authors.
########################################################################

sys=`uname -s`
if [ -r /proc/cpuinfo ]
then
	# It's a Linux box, or something that *looks* like one, such as
	# NetBSD, Cygwin, or the Windows Subsystem for Linux.
	grep -Ec '^processor[[:space:]]+:' /proc/cpuinfo
elif [ "$sys" = "Darwin" -o "$sys" = "OpenBSD" -o "$sys" = "NetBSD" ]
then
	# It's a macOS or BSD box
	/usr/sbin/sysctl -n hw.ncpu
elif [ "$sys" = "FreeBSD" ]
then
    # FreeBSD puts sysctl elsewhere
	/sbin/sysctl -n hw.ncpu
else
	# No known way to find out, so report only 1 core
	echo 1
fi
